# Generated by Django 2.1.2 on 2018-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20201120_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='Chapter_relateId',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='Chapter_label',
            field=models.BooleanField(default=False),
        ),
    ]
