# Generated by Django 2.1.2 on 2018-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20201121_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='Chapter_label',
            field=models.IntegerField(choices=[(1, '一级标题'), (2, '二级标题'), (3, '三级标题'), (4, '四级标题')], default=1, max_length=1, verbose_name='章节等级'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='Chapter_text',
            field=models.CharField(max_length=20, verbose_name='章节名称'),
        ),
    ]
