# Generated by Django 2.1.2 on 2018-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_auto_20201121_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_pageViews',
            field=models.IntegerField(default=0),
        ),
    ]
