# Generated by Django 2.1.2 on 2018-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_chapter_chapter_pageviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_label',
            field=models.IntegerField(choices=[(1, '一级标题'), (2, '二级标题'), (3, '三级标题'), (4, '四级标题')], default=1, verbose_name='章节等级'),
        ),
    ]
