# Generated by Django 2.1.2 on 2018-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_auto_20201121_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
