# Generated by Django 2.1.2 on 2018-12-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_auto_20201121_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_text',
            new_name='chapter_title',
        ),
    ]
