# Generated by Django 2.1.2 on 2018-12-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_auto_20201121_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_content', models.TextField(max_length=1000)),
                ('discuss_userID', models.IntegerField()),
                ('discuss_orderID', models.IntegerField()),
                ('discuss_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_content', models.TextField(max_length=300)),
                ('discuss_userID', models.IntegerField()),
                ('discuss_orderID', models.IntegerField()),
                ('discuss_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.Discuss')),
            ],
        ),
    ]
