# Generated by Django 2.1.2 on 2018-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_discuss_reply'),
    ]
    operations = [
        migrations.AddField(
            model_name='discuss',
            name='discuss_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
