# Generated by Django 2.1.2 on 2018-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_discuss_discuss_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='discuss_title',
            field=models.CharField(max_length=20),
        ),
    ]
