# Generated by Django 2.1.2 on 2018-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_auto_20201121_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='discuss_chapter',
            new_name='reply_chapter',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='discuss_content',
            new_name='reply_content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='discuss_orderID',
            new_name='reply_orderID',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='discuss_userID',
            new_name='reply_userID',
        ),
        migrations.AddField(
            model_name='discuss',
            name='discuss_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
