# Generated by Django 2.1.2 on 2018-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_auto_20201121_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
