# Generated by Django 2.1.2 on 2018-12-15 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_reply_reply_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='discuss_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 15, 17, 47, 13, 134411), null=True),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='discuss_orderID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 15, 17, 47, 13, 134902), null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_orderID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_title',
            field=models.CharField(max_length=20),
        ),
    ]
